### PR TITLE
Clean up `repl` in accordance with Bash best practises

### PR DESCRIPTION
**Pull request by silversquirl**
I tried to keep this as close to the original code style as possible.
Let me know if there are any issues or if you want me to explain any of my changes.

### CODE REVIEW

**Comment by silversquirl** [comment]
For anyone wondering, this isn't a regression from #1 because it runs the command directly rather than capturing and echoing the output.

The only difference that makes is that a command that doesn't end its output with a newline will mess up the prompt a little.

**Comment by icyphox** [comment]
Hey thanks! This is neat. Looks good to me. I haven’t tested it (on mobile), but this preserves output coloring right?

**Comment by silversquirl** [comment]
Yes, colour output is preserved. The reason it wasn't getting preserved is to do with this snippet of code:
```bash
if [ "$stdin" == true ]
then
	out=$(eval "echo $input | $cmd")
else
	out=$(eval "$cmd $input")
fi
echo "$out"
```

When the command's output is captured in a variable, its `stdout` is no longer a tty, it's a pipe. That means that commands which turn on coloring based on the result of `isatty(STDOUT_FILENO)` will not turn it on.

The patch in #1 uses `script` to run the command in a pty, but my patch simply removes the capturing and echoing of command output so that its `stdout` is connected directly to the terminal, as normal.

**Comment by icyphox** [comment]
Ah right, makes sense. Learnt something new today. :)
Merging this now. And thanks again!

**Pull request merged**
